//
//  Applozic.h
//  Applozic
//
//  Created by Devashish on 07/10/15.
//  Copyright © 2015 applozic Inc. All rights reserved.
//

#import <UIKit/UIKit.h>

//! Project version number for Applozic.
FOUNDATION_EXPORT double ApplozicVersionNumber;

//! Project version string for Applozic.
FOUNDATION_EXPORT const unsigned char ApplozicVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import "PublicHeader.h"

#import "ALRegisterUserClientService.h"
#import "ALContact.h"
#import "ALAudioVideoBaseVC.h"
#import "ALVOIPNotificationHandler.h"
#import "ALChatLauncher.h"
#import "ALRegistrationResponse.h"
#import "ALPushNotificationService.h"
#import "ALUser.h"
#import "ALUserDefaultsHandler.h"
#import "ALJson.h"
#import "ALMessagesViewController.h"
#import "ALConstant.h"
#import "ALChatViewController.h"
#import "KAProgressLabel.h"
#import "ALMessageClientService.h"
#import "ALDBHandler.h"
#import "ALChatCell.h"
#import "ALMessage.h"
#import "TPPropertyAnimation.h"
#import "ALContactCell.h"
#import "ALMessageDBService.h"
#import "ALLocationManager.h"
#import "ALMessageService.h"
#import "DB_FileMetaInfo.h"
#import "ALRequestHandler.h"
#import "ALMessageList.h"
#import "ALNewContactCell.h"
#import "ALSyncMessageFeed.h"
#import "ALUtilityClass.h"
#import "ALNewContactsViewController.h"
#import "Applozic.h"
#import "ALResponseHandler.h"
#import "ALImagePickerHandler.h"
#import "ALFileMetaInfo.h"
#import "ALNotificationView.h"
#import "DB_CONTACT.h"
#import "ALImageCell.h"
#import "ALConnection.h"
#import "ALBaseViewController.h"
#import "ALConnectionQueueHandler.h"
#import "DB_Message.h"
#import "UIImage+Utility.h"
#import "ALUserDetail.h"
#import "ALDataNetworkConnection.h"
#import "ALAppLocalNotifications.h"
#import "DB_ConversationProxy.h"
#import "ALConversationProxy.h"
#import "ALConversationService.h"
#import "ALApplozicSettings.h"
#import "ALContactsResponse.h"
#import "ALContactService.h"
#import "ALUserService.h"
#import "ALCollectionReusableView.h"
#import "ALContactMessageCell.h"
#import "ALCustomCell.h"
#import "ALDocumentsCell.h"
#import "ALGroupCreationViewController.h"
#import "ALGroupDetailViewController.h"
#import "ALImageActivity.h"
#import "ALImagePickerController.h"
#import "ALLocationCell.h"
#import "ALMessageInfoViewController.h"
#import "ALMultipleAttachmentCell.h"
#import "ALReceiverUserProfileVC.h"
#import "ALUserProfileVC.h"
#import "ALChannelInfo.h"
#import "ALConversationClientService.h"
#import "ALConversationCreateResponse.h"
#import "ALConversationDBService.h"
#import "ALLogs.h"
#import "ALMQTTConversationService.h"
#import "ALMultipleAttachmentView.h"
#import "ALPushAssist.h"
#import "ALSendMessageResponse.h"
#import "ALShowImageViewController.h"
#import "ALVideoCell.h"
#import "TSMessage.h"
#import "TSMessageView.h"
#import "TSBlurView.h"
#import "NSString+Encode.h"
#import "HexColors.h"
#import "ALUserDetailListFeed.h"
#import "ALNavigationController.h"
#import "ALMessageServiceWrapper.h"
#import "ALSubViewController.h"
#import "MessageReplyView.h"
#import "AlChannelInfoModel.h"
#import "AlChannelResponse.h"
#import "AlChannelFeedResponse.h"
#import "ALGroupUser.h"

#import "ALChannelMsgCell.h"
#import "ALChannelUser.h"
#import "ALVOIPCell.h"
#import "ALApplicationInfo.h"
#import "MQTTDecoder.h"
#import "MQTTInMemoryPersistence.h"
#import "MQTTLog.h"
#import "MQTTSSLSecurityPolicyDecoder.h"
#import "MQTTSessionManager.h"
#import "MQTTSSLSecurityPolicyEncoder.h"
